### PR TITLE
Updated the README

### PR DESCRIPTION
**Pull request by muneebullashariff**
Included the **verilator** simulator to the readme section of supported simulators

### CODE REVIEW

**Comment by muneebullashariff** [comment]
I was not able to add the reviewer to this pull request.

**Comment by svenka3** [comment]
Thanks, please consider submitting to the original svunit repo: https://github.com/svunit/svunit 

BTW - since you are interested in opensource, consider using and contributing to PySlint via https://github.com/AsFigo/pyslint

**Comment by muneebullashariff** [comment]
@svenka3 Many thanks for your response. This pull request has the required changes and I have created it under SVUnit official GitHub.

With regards to pyslint project, I am wondering the use case of this project because I using Verible project from Google for linting.

**Comment by muneebullashariff** [comment]
Will submit a new pull request with appropriate changes

**Pull request closed without merging**
