### PR TITLE
Add support for Xilinx Vivado Simulator

### LINKED ISSUE #148: Add support for Xilinx Vivado XSim
SVUnit does not support Xilinx Vivado XSim. I would love to see this supported.

The magic that is needed to run a UVM test (for example) in XSim is:

`Vivado -mode batch -source run.tcl`

Where run.tcl is:

```
exec xvlog -sv -f files.f -L uvm ;
exec xelab top -relax -s top -timescale 1ns/1ps ;
exec xsim top -testplusarg UVM_TESTNAME=basic_test -testplusarg UVM_VERBOSITY=UVM_LOW -runall
```

### PR DESCRIPTION
**Pull request by tudortimi**
Fixes #148

### CODE REVIEW

**Comment by tudortimi** [comment]
@PeterMonsson This took longer than expected. Your previous work helped. I also noticed, though, that many of the issues you had weren't present anymore.

**Comment by tudortimi** [comment]
I think my "favorite" is how things generally work in the tool in isolation, but break in a real project.

**Comment by PeterMonsson** [comment]
Nice! What version did you use?

**Comment by tudortimi** [comment]
I used 2023.1, I think it's the latest at the time of writing.

**Comment by trosenkranz** [comment]
> I used 2023.1, I think it's the latest at the time of writing.

@tudortimi Version 2023.2 came out just a couple of days ago. I have installed it on my workstation at work and will check if your changes work with my test cases and report back to you.

I'll also run the testframework, SVUnit comes with.

And thanks for your work on this.

**Comment by trosenkranz** [comment]
@tudortimi I have tried to execute the tests in the *test/*-subdirectroy as described in the *README*. It didn't work.

I use an Ubuntu 22.04 LTS with python3.10. When I install the requirements from the *requirements.txt* these errors
([error_with_packages_from_requirements.txt](https://github.com/svunit/svunit/files/13282565/error_with_packages_from_requirements.txt)) occur.

I updated the packages with pip using the command from [StackOverflow](https://stackoverflow.com/questions/2720014/how-to-upgrade-all-python-packages-with-pip). Then some tests work but there are also errors ([report_html.zip](https://github.com/svunit/svunit/files/13282684/report_html.zip)).

What python version do you use and did you update some packages so that the *requirements.txt* is out of date?

**Comment by PeterMonsson** [comment]
I had this problem today. I updated pytest in requirements.txt to 7.4.3 for it to work.

**Comment by trosenkranz** [comment]
I tried your solution and it worked to get *pytest* running but Vivado 2023.2 now crashes with Segmentation Faults ([report_html_Vivado2023.2.zip](https://github.com/svunit/svunit/files/13294701/report_html_Vivado2023.2.zip)). I've seen a similar behavior when I tried to execute the SVUnit-Tests of one of my IP-Cores.

With Vivado 2023.1 it works, but there are warnings during compilation/elaboration as reported [here](https://github.com/svunit/svunit/issues/282#issue-1978316768) before.

When I apply this patch ([local_modifications.patch.txt](https://github.com/svunit/svunit/files/13294756/local_modifications.patch.txt)) then *$fatal* tests fail ([report_html_Vivado2023.1.zip](https://github.com/svunit/svunit/files/13294735/report_html_Vivado2023.1.zip)). I assume it is due to the *finish_number* set to zero in the *$fatal* call.

**Comment by trosenkranz** [comment]
Just verified, that it is due to the *finish_number*. With 1 it works.

**Comment by trosenkranz** [comment]
> I tried your solution and it worked to get _pytest_ running but Vivado 2023.2 now crashes with Segmentation Faults ([report_html_Vivado2023.2.zip](https://github.com/svunit/svunit/files/13294701/report_html_Vivado2023.2.zip)). I've seen a similar behavior when I tried to execute the SVUnit-Tests of one of my IP-Cores.

I have made an interesting observation: When calling `xelab` with the option `-debug typical` it works fine. I have tested it with this (quick and dirty) [svunit.patch.txt](https://github.com/svunit/svunit/files/13350884/svunit.patch.txt) applied. It requires #290 to be applied.

**Comment by BenjaminGittins** [comment]
I forked the latest version of the code with xilinx support and made some adjustments to improve Xilinx support around the various issues i raised.  Find my notes about this here: https://github.com/svunit/svunit/issues/291#issuecomment-1826259914

**Pull request merged**
