### PR TITLE
Adds -uvm_opts command line argument.

### PR DESCRIPTION
**Pull request by edcote**
Add new command line argument -uvm_opts. These options are passed directly to simulator following -uvm.

### CODE REVIEW

**Comment by edcote** [comment]
May not be needed because users could always pass via `--c_args "--whatever options --you want"`.

Maybe its desired because --uvm could have sub options --uvm_opts? Either way. I'm OK.

**Comment by tudortimi** [comment]
For some simulators, it's do-able to use `-c_arg` or to just add the options to `svunit.f`. For VCS, I have the impression it won't work, because the user would need to override what SVUnit tries to insert.

**Comment by tudortimi** [comment]
Yep, starting `vcs -ntb_opts uvm -ntb_opts uvm-1.2` doesn't set UVM 1.2, but keeps 1.1d. (I for one would have also expected VCS to issue an error message...)

**Comment by tudortimi** [comment]
I'd see `-uvm_opts` more as a replacement for what SVUnit inserts by default:

- if `-uvm_opts` passed, use **just** args from user to compile UVM
- else, use built in options

**Comment by tudortimi** [comment]
I'm also wondering whether a `-no_builtin_uvm_opts` option isn't better. I'd argue that users should want their options stored in a configuration file (i.e. `svunit.f`), so they can only call `runSVUnit`, with maybe just options for filtering tests.

**Pull request closed without merging**
